#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickrage/.git ]] && \
	#git clone https://github.com/SickRage/SickRage.git /app/sickrage
	git clone https://donna.devices.wvvw.me/sickrage/sickrage.git
# permissions
chown -R abc:abc \
	/app \
	/config
